import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const originalCwd = process.cwd();
const temp = fs.mkdtempSync(path.join(os.tmpdir(), "npa-review-test-"));
const hash = (file) => createHash("sha256").update(fs.readFileSync(file)).digest("hex").toUpperCase();
const write = (file, value) => fs.writeFileSync(path.join(temp, file), JSON.stringify(value));
const template = (name) => JSON.parse(fs.readFileSync(path.join(packageRoot, "assets", name), "utf8").replace(/\{\{[^}]+\}\}/g, "fixture"));

try {
  process.chdir(temp);
  const { runCli, countCjk } = await import("./validate_prose_review_gate.mjs");
  assert.equal(countCjk("甲乙a。"), 2);
  fs.writeFileSync("prose.txt", "她带上门，走下楼梯。\n");
  fs.writeFileSync("outline.txt", "人物离开房间。\n");
  const prose = { path: "prose.txt", sha256: hash("prose.txt") };
  const outline = { path: "outline.txt", sha256: hash("outline.txt") };
  const a = template("outline-expression-coverage-audit-v2.template.json");
  Object.assign(a, { audit_id: "report-a", object_id: "article", prose, outline, task_id: "task-a", context_id: "context-a", closed: true, coverage_result: "PASS" });
  a.scene_coverage[0].status = "PRESENT";
  const b = template("narrative-closure-audit-v1.template.json");
  Object.assign(b, { audit_id: "report-b", object_id: "article", prose, outline });
  Object.assign(b.auditor, { task_id: "task-b", context_id: "context-b" });
  write("a.json", a);
  write("b.json", b);
  write("segments.json", { submission_sha256: prose.sha256, boundary_unit: "UTF8_BYTES", coverage_mode: "FULL_DOCUMENT", segments: [{ utf8_start: 0, utf8_end: fs.statSync("prose.txt").size }] });
  const segmentRun = spawnSync(process.env.PYTHON || "python", ["-X", "utf8", "-B", path.join(packageRoot, "scripts", "check_segment_semantic_boundaries.py"), path.join(temp, "prose.txt"), path.join(temp, "segments.json")], { encoding: "utf8" });
  assert.equal(segmentRun.status, 0, segmentRun.stderr + segmentRun.stdout);
  const segment = JSON.parse(segmentRun.stdout);
  assert.equal(segment.result, "PASS");
  write("segment-audit.json", segment);
  let sequence = 0;
  const invoke = (extra = [], includeReports = true) => {
    let stdout = "";
    const args = ["--prose", "prose.txt", "--object-id", "article", "--result", `result-${sequence++}.json`];
    if (includeReports) args.push("--outline-completion-audit", "a.json", "--narrative-closure-audit", "b.json", "--segment-boundary-audit", "segment-audit.json");
    const status = runCli([...args, ...extra], { stdout: { write: (value) => { stdout += value; } } });
    return { status, result: JSON.parse(stdout) };
  };
  const valid = invoke();
  assert.equal(valid.status, 0, JSON.stringify(valid.result));
  assert.equal(valid.result.minimum_cjk, null);
  assert.equal(valid.result.length_floor_status, "UNSPECIFIED");
  assert.equal(invoke(["--minimum-cjk", "100"]).result.error_code, "PROSE_CJK_BELOW_USER_MINIMUM");
  assert.equal(invoke(["--minimum-cjk", "-1"]).status, 2);
  assert.equal(invoke([], false).result.error_code, "OUTLINE_COMPLETION_AUDIT_REQUIRED");
  b.auditor.task_id = "task-a";
  write("b.json", b);
  assert.equal(invoke().result.error_code, "AUDIT_REPORT_PAIR_TASK_ID_COLLISION");
  b.auditor.task_id = "task-b";
  b.auditor.peer_report_read = true;
  write("b.json", b);
  assert.equal(invoke().result.error_code, "NARRATIVE_CLOSURE_AUDIT_INDEPENDENCE_INVALID");
  b.auditor.peer_report_read = false;
  delete b.scene_matrix[0].scene_evidence.entry_state;
  write("b.json", b);
  assert.equal(invoke().result.error_code, "NARRATIVE_CLOSURE_AUDIT_SCENE_EVIDENCE_MISSING");
  b.scene_matrix[0].scene_evidence.entry_state = "room";
  b.scene_matrix[0].dialogue_action_handshake.unresolved_turn_count = 1;
  write("b.json", b);
  assert.equal(invoke().result.error_code, "NARRATIVE_CLOSURE_AUDIT_DIALOGUE_HANDSHAKE_INVALID");
  b.scene_matrix[0].dialogue_action_handshake.unresolved_turn_count = 0;
  write("b.json", b);
  segment.review_flag_count = 1;
  write("segment-audit.json", segment);
  assert.equal(invoke().result.error_code, "SEGMENT_BOUNDARY_AUDIT_FLAGS_PRESENT");
  segment.review_flag_count = 0;
  write("segment-audit.json", segment);
  fs.appendFileSync("prose.txt", "天黑了。");
  assert.equal(invoke().result.error_code, "OUTLINE_COMPLETION_AUDIT_PROSE_MISMATCH");
  console.log("REVIEW_GATE_SELF_TEST=PASS");
} finally {
  process.chdir(originalCwd);
  assert.equal(path.dirname(fs.realpathSync(temp)), fs.realpathSync(os.tmpdir()));
  assert.ok(path.basename(temp).startsWith("npa-review-test-"));
  fs.rmSync(temp, { recursive: true });
}
